# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningdjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='grade',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
